### ISSUE TITLE
multiple servers and switching servers

### ISSUE THREAD

**Issue by sebastianelsner** [mikrosimage/PuliMonitor#2]
Do we need to be able to specify multiple servers in the settings file?
Do we need to be able to switch them in the GUI? Whats the prefered method: via logging out and logging in or via a simple switch server command in the menu?

**Comment by samson-jerome** [comment]
It is very important to be able to switch server in the GUI, the HTTP layer used make this quite easy to address I think. I'm not sure it should be necessary to logout/login as servers don't handle connection lifetime...
A simple drop-down list indicating the base URL should be fine.

**Comment by sebastianelsner** [comment]
implemented in current develop branch.
